### ISSUE TITLE
UI 프레임워크 선정

### ISSUE THREAD

**Issue by okps123** [okps123/2019-kmucs-osp#3]
1. [Bulma](http://bulma.io)
2. [Semantic UI](https://semantic-ui.com)

React Component 형태보다는 수정이 용이로운 CSS Framework가 나을 듯 싶습니다.
그 중에서도 두개가 포멀한 UI 프레임워크인 것 같습니다.

아니면 다른 프레임워크도 알려주시면 조사해볼게요~

**Comment by ChanHHOO** [comment]
저도 조사해보고 다시 말씀드리겠슴니당

**Comment by okps123** [comment]
@ChanHHOO 설정은 제가 해서 풀 리퀘스트 할게요

**Comment by okps123** [comment]
Smeantic-UI로 결정하였습니다.
