### ISSUE TITLE
기획 발표 자료 준비

### ISSUE THREAD

**Issue by okps123** [okps123/2019-kmucs-osp#4]
준비되면 발표 자료도 Github에 올려주시는게 평가에 도움이 될 것 같아요.
발표 자료는 어떻게 준비되고 있나요?

**Comment by jhg2957** [comment]
발표 제안서 (word)
[https://docs.google.com/document/d/1-CLOAAusTKAZSpF_ki2tMLAKVJjXqDkgURfaOJKsrMM/edit?usp=sharing](url)

발표 PPT
[https://docs.google.com/presentation/d/1ls6OYneoRtCGK9jmo4a375lcFbi1C9WwEWdbg9-vAfM/edit?usp=sharing](url)
